FROM registry.access.redhat.com/ubi8/python-312

# Install uv pointing to the uv image and coping from there
# /uv and /uvx are the source files copied from the uv image
# /bin is the destination
COPY --from=ghcr.io/astral-sh/uv:0.8.12 /uv /uvx /bin/

# Set working directory
WORKDIR /app

# Copy dependency files
COPY pyproject.toml uv.lock ./

# Install dependencies
RUN uv sync
ENV VIRTUAL_ENV=.venv
ENV PATH=".venv/bin:$PATH"

COPY . .

# Expose the Gradio port
EXPOSE 7861

# Run the Gradio app
ENTRYPOINT ["uv", "run","app.py"]
